package py.gov.hacienda.digital.doc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-10-15T14:51:18.010-02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "DocumentoFirmaDigitalService", 
                  wsdlLocation = "file:/C:/workspace_ws_tx/WService_TX/WebContent/objetoPdfService.wsdl",
                  targetNamespace = "http://doc.digital.hacienda.gov.py/") 
public class DocumentoFirmaDigitalService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://doc.digital.hacienda.gov.py/", "DocumentoFirmaDigitalService");
    public final static QName DocumentoFirmaDigitalEndPointPort = new QName("http://doc.digital.hacienda.gov.py/", "DocumentoFirmaDigitalEndPointPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace_ws_tx/WService_TX/WebContent/objetoPdfService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DocumentoFirmaDigitalService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace_ws_tx/WService_TX/WebContent/objetoPdfService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DocumentoFirmaDigitalService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DocumentoFirmaDigitalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentoFirmaDigitalService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DocumentoFirmaDigitalService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DocumentoFirmaDigitalService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DocumentoFirmaDigitalService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DocumentoFirmaDigitalEndPoint
     */
    @WebEndpoint(name = "DocumentoFirmaDigitalEndPointPort")
    public DocumentoFirmaDigitalEndPoint getDocumentoFirmaDigitalEndPointPort() {
        return super.getPort(DocumentoFirmaDigitalEndPointPort, DocumentoFirmaDigitalEndPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentoFirmaDigitalEndPoint
     */
    @WebEndpoint(name = "DocumentoFirmaDigitalEndPointPort")
    public DocumentoFirmaDigitalEndPoint getDocumentoFirmaDigitalEndPointPort(WebServiceFeature... features) {
        return super.getPort(DocumentoFirmaDigitalEndPointPort, DocumentoFirmaDigitalEndPoint.class, features);
    }

}
