
package py.gov.hacienda.digital.doc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-10-15T14:51:17.930-02:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "WsException", targetNamespace = "http://doc.digital.hacienda.gov.py/")
public class WsException_Exception extends Exception {
    
    private py.gov.hacienda.digital.doc.WsException wsException;

    public WsException_Exception() {
        super();
    }
    
    public WsException_Exception(String message) {
        super(message);
    }
    
    public WsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WsException_Exception(String message, py.gov.hacienda.digital.doc.WsException wsException) {
        super(message);
        this.wsException = wsException;
    }

    public WsException_Exception(String message, py.gov.hacienda.digital.doc.WsException wsException, Throwable cause) {
        super(message, cause);
        this.wsException = wsException;
    }

    public py.gov.hacienda.digital.doc.WsException getFaultInfo() {
        return this.wsException;
    }
}
